config/routes.rb
Rails.application.routes.draw do
  get 'photo/index/:id' => 'photo#index', as: 'user_photos'
  get 'user/index' => 'user#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  has_many :comments
  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.all
    @user_all = User.all
  end

  def display_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.first_name
  end
  helper_method :display_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photosite2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<body>
<h1 style="font-size: 30pt;text-align: center;">Photo page</h1>

<p id="p02"><u>Photo of</u> :- <b><i><%= link_to @user.first_name %> <%= link_to @user.last_name %></i></b></p>
<% @photos.each do |photo| %>
  <%= image_tag("/assets/#{photo.file_name}") %>
  <p id="p02"><u>Photo created on</u> :- <b><i><%=photo.date_time %> </i></b></p>

  <% @comments.where("photo_id=?",photo.id).each do |comment| %>

    <p id="p01"><b><i> <u>Comment</u> :- <%=comment.comment_text %></i></b></p>
    <p id="p01"><b><i> <u>Created on</u> :- <%=comment.date_time %></i></b></p>
    <p id="p01"><b><i> <u>Posted by</u> :- <%=link_to display_name(comment.user_id), user_photos_path(comment.user_id) %></i></b></p>
  <% end %>

<% end %>

</body>

app/views/user/index.html.erb
<h1> Photosite User List</h1>
<body>
<table>
  <tr style="...">
    <th style="..."> Index </th>
    <th style="..."> Firstname </th>
    <th style="..."> Lastname </th>

  </tr>
  <% @users.each do |user| %>
    <tr>
      <th style="..."><%= link_to user.id, user_photos_path(user.id) %> </th>
      <th style="..."><%= link_to user.first_name, user_photos_path(user.id) %> </th>
      <th style="..."><%= link_to user.last_name, user_photos_path(user.id) %> </th>
    </tr>

  <%end %>
</table>
</body>